# Generated by Django 5.2.17 on 2026-09-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('asset_type', models.CharField(blank=True, default='', max_length=32)),
                ('asset_id', models.IntegerField(blank=True, null=True)),
                ('asset_value', models.CharField(blank=True, db_index=True, default='', max_length=2048)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=16)),
                ('confidence', models.CharField(default='unknown', max_length=16)),
                ('source', models.CharField(blank=True, default='', max_length=128)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='targets.target')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='discord', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('BATCHED', 'Batched'), ('SUPPRESSED', 'Suppressed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('payload_preview', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'created_at'], name='events_even_event_t_e518f4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['target', 'created_at'], name='events_even_target__a91791_idx'),
        ),
    ]
