# Generated by Django 5.2.17 on 2026-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('BATCHED', 'Batched'), ('SUPPRESSED', 'Suppressed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('THROTTLED', 'Throttled'), ('DEDUPLICATED', 'Deduplicated')], db_index=True, default='PENDING', max_length=16),
        ),
    ]
