# Generated by Django 5.2.17 on 2026-09-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('root_domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=16)),
                ('authorization_status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending')], default='AUTHORIZED', max_length=16)),
                ('authorization_expires_at', models.DateTimeField(blank=True, null=True)),
                ('auth_warning_days', models.IntegerField(default=7)),
                ('baseline_status', models.CharField(db_index=True, default='NOT_STARTED', max_length=32)),
                ('baseline_started_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_completed_at', models.DateTimeField(blank=True, null=True)),
                ('wildcard_detected', models.BooleanField(default=False)),
                ('wildcard_ips', models.JSONField(blank=True, default=list)),
                ('wildcard_cnames', models.JSONField(blank=True, default=list)),
                ('scan_config', models.JSONField(blank=True, default=dict)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('next_scan', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['root_domain'],
            },
        ),
    ]
