# Generated by Django 5.2.17 on 2026-09-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(db_index=True, max_length=64)),
                ('stage', models.CharField(blank=True, default='', max_length=64)),
                ('tool', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused'), ('SKIPPED', 'Skipped')], db_index=True, default='QUEUED', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('command_redacted', models.TextField(blank=True, default='')),
                ('run_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('baseline_mode', models.BooleanField(default=False)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('worker', models.CharField(blank=True, default='', max_length=128)),
                ('error', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='targets.target')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], db_index=True, default='INFO', max_length=16)),
                ('stage', models.CharField(blank=True, default='', max_length=64)),
                ('tool', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('message', models.TextField()),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.scanjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
