# Generated by Django 5.2.17 on 2026-09-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_discovered_by_job_and_more'),
        ('jobs', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='asset_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='asset_value',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='current_stage',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='jobs.scanjob'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='trigger',
            field=models.CharField(db_index=True, default='manual', max_length=32),
        ),
        migrations.CreateModel(
            name='JSAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(db_index=True, default='NEW_JS', max_length=32)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('current_stage', models.CharField(db_index=True, default='QUEUED', max_length=32)),
                ('progress', models.IntegerField(default=0)),
                ('stages', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('js', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='assets.javascriptasset')),
                ('parent_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='js_analyses', to='jobs.scanjob')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='js_jobs', to='targets.target')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JSAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(db_index=True, default='INFO', max_length=16)),
                ('stage', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('tool', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.jsanalysisjob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
