# Generated by Django 5.2.17 on 2026-09-26 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVESyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128, unique=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('info', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=16)),
                ('event_ids', models.JSONField(blank=True, default=list)),
                ('window_ends_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('RUNNING', 'Running'), ('COMPLETE', 'Complete')], db_index=True, default='NOT_STARTED', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='targets.target')),
            ],
        ),
    ]
