# Generated by Django 5.2.17 on 2026-09-26 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('allow_domain', 'Allowed domain'), ('exclude_host', 'Excluded host'), ('allow_ip', 'Allowed IP/CIDR'), ('exclude_ip', 'Excluded IP/CIDR'), ('port', 'Port/range'), ('rate_limit', 'Rate limit'), ('concurrency', 'Concurrency')], db_index=True, max_length=32)),
                ('value', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scope_rules', to='targets.target')),
            ],
            options={
                'ordering': ['rule_type', 'value'],
            },
        ),
    ]
