# Generated by Django 5.2.17 on 2026-09-26 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='discovered_by_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_assets', to='jobs.scanjob'),
        ),
        migrations.AddField(
            model_name='javascriptasset',
            name='discovered_from',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
